### ISSUE TITLE
$logfile problems

### ISSUE THREAD

**Issue by ethaniel** [bstillman/mariadb-backup#28]
When I started the script, here are the errors that I got:

/usr/bin/bgbackup.sh: line 33: : No such file or catalog
/usr/bin/bgbackup.sh: line 33: : No such file or catalog
/usr/bin/bgbackup.sh: line 17: : No such file or catalog

The $logfile var is empty.

**Comment by bstillman** [comment]
There's a fix for this in the works. Just debating whether to fail and exit or use /tmp to log the failure and email. There's a pull request pending. I'll update this issue when it's fixed (probably today).

**Comment by bstillman** [comment]
By the way, this usually happens when the config file isn't found.

**Comment by ethaniel** [comment]
The config file is OK. The backup started normally. It's just that there are no logs (only syslog).

**Comment by bstillman** [comment]
Do you have logpath empty, and syslog=yes?

**Comment by ethaniel** [comment]
Never mind. Problem is gone now. Looks like I had an error in the config.
