### ISSUE TITLE
Add the option to use mariabackup

### ISSUE THREAD

**Issue by Infern1** [bstillman/mariadb-backup#37]
MariaDB has it's own  backup package mariabackup.

This has the same options as xtrabackup, so wouldn't be a lot of work.

See here for details: https://mariadb.com/kb/en/mariadb/mariadb-backup-overview/

**Comment by bstillman** [comment]
I plan on creating a new version for MariaDB Backup. It isn't currently fully compatible with this script.

**Comment by michaeldg** [comment]
What's not compatible about it? Afaik there are only some features such as backup-side encryption dropped.
