### ISSUE TITLE
Failed to create incremental backup

### ISSUE THREAD

**Issue by Trungma1988** [bstillman/mariadb-backup#39]
Hello,

I got an issue when creating incremental backup with error "xtrabackup: error: failed to read metadata from /backups/full-2018-02-02_13-20-51//xtrabackup_checkpoints"

What should I do?

Regards,
Trung Ma

**Comment by bstillman** [comment]
What version of MySQL/MariaDB are you using? Sounds almost like you're running into this: https://bugs.launchpad.net/percona-xtrabackup/+bug/655584

**Comment by Trungma1988** [comment]
MySQL version is 10.2.12-MariaDB. I checked file xtrabackup_checkpoints on the full backup folder, and don't see any record.

![image](https://user-images.githubusercontent.com/18327251/35787229-3da52eaa-0a5f-11e8-8bef-b787b64376ca.png)

**Comment by Trungma1988** [comment]
When I changed to "encrypt = no" on bgbackup.sh file. I can create an incremental backup. 
![image](https://user-images.githubusercontent.com/18327251/35788113-c17c2fd4-0a65-11e8-8145-c2f6269971b1.png)

**Comment by bstillman** [comment]
Do you have the log file from the successful full backup?

**Comment by Trungma1988** [comment]
Yes please
[log.zip](https://github.com/bstillman/bgbackup/files/1697481/log.zip)

**Comment by bstillman** [comment]
Can you verify you have xbcrypt installed? If not, install and try again. Looks like I need to add some logic to check for xbcrypt.

**Comment by Trungma1988** [comment]
Hello Ben,

It's already installed. After enable debug on bgbackup.cnf. I think the problem is my key generation.
![image](https://user-images.githubusercontent.com/18327251/35962205-27570eee-0ce3-11e8-89f7-f2512fd63dca.png)

**Comment by bstillman** [comment]
Sorry for the delayed reply. Somehow I missed this. Looks like you have a newline in the key file. Is that possible? Did you try regenerating the key?

```echo -n $(openssl rand -base64 24) > /etc/my.cnf.d/backupscript.key```

When you cat the key, it should look like:

```[root@web1 my.cnf.d]# echo -n $(openssl rand -base64 24) > /etc/my.cnf.d/backupscript.key
[root@web1 my.cnf.d]# cat /etc/my.cnf.d/backupscript.key
AGAPZ7e4525jd3GxncEiVudc8MZpXw3i[root@web1 my.cnf.d]#
[root@web1 my.cnf.d]#```

Notice the lack of new line after the end of the key, so the prompt appears at the end of the key.

**Comment by bstillman** [comment]
Closing due to no reply.
