### ISSUE TITLE
InnoDB: Can't create file when --innodb-read-only is set

### ISSUE THREAD

**Issue by mshiriv** [bstillman/mariadb-backup#43]
hello,
when I try to run script I receive bellow error:

80902 15:52:57 >> log scanned up to (9539434633)
**InnoDB: Can't create file '/var/lib/mysql/mysql/ibdata1' when --innodb-read-only is set**
xtrabackup: could not find data files at the specified datadir
xtrabackup: error: xb_load_tablespaces() failed witherror code 11
2018-09-02-15:52:57 --> Full backup FAILED

database version:
mysql  Ver 15.1 Distrib 10.1.32-MariaDB, for Linux (x86_64) using readline 5.1

operating system:
CentOS Linux release 7.4.1708 (Core)

best regards.

**Comment by bstillman** [comment]
Looks like an xtrabackup configuration issue. That error message isn't from the script. Sorry.
