### ISSUE TITLE
What is bgbackup?

### ISSUE THREAD

**Issue by willfong** [bstillman/mariadb-backup#8]
There really isn't a clear description of _what_ bgbackup is. The main description says what server software it is compatible with, and some details of what part of xtrabackup that it supports. But that doesn't say what bgbackup is. I don't really know the full scope of this tool as well, so I created this issue to brainstorm and discuss.

To start, I think it should say something along the lines of:

> bgbackup is a wrapper script for setting up a daily database backup routine. It can be configured to run different types of backups, and send a status email upon completion.

Still a work in progress...

**Comment by tanji** [comment]
Updated in d272a313aadf0543b66b3f6eaa7615a88620ae90, thanks for the suggestion!
I'm leaving this open if you or Ben have other ideas.
